# DAT 19: Homework 1 Assignment

## Instructions

In this assignment, we will explore the passenger list of the Titanic, as provided in a well-known [Kaggle](https://www.kaggle.com) competition. For this assignment, we are concerned only with initial exploration. Please answer the specific questions listed below.

The dataset is a list of passengers. The second column of the dataset is the label for each person indicating whether that person survived (1) or did not survive (0). The data is described in more detail below.

There is no need to download the data from Kaggle. We have provided the titanic.csv dataset for you in the same  directory as this assignment.

Please do all your analysis to answer the questions below in this Jupyter notebook. Show your work. Questions 10, 13, and 14 ask for your thoughts as a few sentences (regular prose, not code :-).

**Please submit your completed notebook by 11:59PM on Thursday, December 17.**

## About the Data

```
VARIABLE DESCRIPTIONS:
survival        Survival
                (0 = No; 1 = Yes)
pclass          Passenger Class
                (1 = 1st; 2 = 2nd; 3 = 3rd)
name            Name
sex             Sex
age             Age
sibsp           Number of Siblings/Spouses Aboard
parch           Number of Parents/Children Aboard
ticket          Ticket Number
fare            Passenger Fare
cabin           Cabin
embarked        Port of Embarkation
                (C = Cherbourg; Q = Queenstown; S = Southampton)

SPECIAL NOTES:
Pclass is a proxy for socio-economic status (SES)
 1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower

Age is in Years; Fractional if Age less than One (1)
 If the Age is Estimated, it is in the form xx.5

With respect to the family relation variables (i.e. sibsp and parch)
some relations were ignored.  The following are the definitions used
for sibsp and parch.

Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiances Ignored)
Parent:   Mother or Father of Passenger Aboard Titanic
Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic

Other family relatives excluded from this study include cousins,
nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
only with a nanny, therefore parch=0 for them.  As well, some
travelled with very close friends or neighbors in a village, however,
the definitions do not support such relations.
```

### Load Data

Start by loading the Titanic data into a numpy array. The code to do this is included below to get you started.

In [7]:
# We'll use the csv module from the Python standard library to read each row of our input data file
#   into a list that we then convert into a numpy array.

import csv as csv #csv will denote all csv files
import numpy as np

file_object = csv.reader(open('titanic.csv', 'rb'))
header = file_object.next() #First, let's strip off the header

data = [] 
for row in file_object:
    data.append(row) #data will be a list of indexes

data = np.array(data) #Turn our Python list into a numpy array

# Let's see what our data looks like. Notice what type the data appears to be inside the numpy array.

#print header
print type(data)
print data.shape

print data[:10,:]
print '\n' + '...'
print data[-1,:]

<type 'numpy.ndarray'>
(891, 12)
[['1' '0' '3' 'Braund, Mr. Owen Harris' 'male' '22' '1' '0' 'A/5 21171'
  '7.25' '' 'S']
 ['2' '1' '1' 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
  'female' '38' '1' '0' 'PC 17599' '71.2833' 'C85' 'C']
 ['3' '1' '3' 'Heikkinen, Miss. Laina' 'female' '26' '0' '0'
  'STON/O2. 3101282' '7.925' '' 'S']
 ['4' '1' '1' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' 'female' '35'
  '1' '0' '113803' '53.1' 'C123' 'S']
 ['5' '0' '3' 'Allen, Mr. William Henry' 'male' '35' '0' '0' '373450'
  '8.05' '' 'S']
 ['6' '0' '3' 'Moran, Mr. James' 'male' '' '0' '0' '330877' '8.4583' '' 'Q']
 ['7' '0' '1' 'McCarthy, Mr. Timothy J' 'male' '54' '0' '0' '17463'
  '51.8625' 'E46' 'S']
 ['8' '0' '3' 'Palsson, Master. Gosta Leonard' 'male' '2' '3' '1' '349909'
  '21.075' '' 'S']
 ['9' '1' '3' 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)' 'female'
  '27' '0' '2' '347742' '11.1333' '' 'S']
 ['10' '1' '2' 'Nasser, Mrs. Nicholas (Adele Achem)' 'female' '14' '1' '0'
  

## Homework Questions

**1) How many passengers are in our passenger list? For this assignment, we’ll assume our dataset represents the full passenger list for the Titanic.**

In [26]:
# Your code here for num_passengers. Uncomment the line below to format your answer.

data_shape = data.shape
#print type(data_shape)

row = data_shape[0]
#print row

num_passengers = row

print 'There are ' + str(num_passengers) + ' passengers in our list.'

There are 891 passengers in our list.


**2) What is the overall survival rate (as a percentage of total passengers in our list)?**

In [82]:
#differentiate between number survived / 

#need to turn num_passengers into a list of ints

#num_passengers_list = [:,num_passengers]


num_passenger_l = range(0, num_passengers)
print type(num_passenger_l)


#for num in num_passenger_l:
    

#num_passengers_list.append(num_passengers+1)
#print num_passengers_list



<type 'list'>


In [115]:
#HINT: You may want to import another module here
#assuming 0 is dead, and 1 is alive

survived_sex = []
count = 0

num_passenger_l = range(0, num_passengers)
print type(num_passenger_l)

for val in num_passenger_l: #val is an int
    if ((data[val][1]) == "1"):
        survived_sex.append(data[val][4])
        count = count + 1
        
num_survived = count #setting num_survived as the counter

survival_rate = float(num_survived) / float(num_passengers)
#print type(num_survived)
#print type(num_passengers)
#print survival_rate

#Your code here to calculate num_survived and survival_rate. 
#Again, we've provided some code you can use to format your answer.



print 'Of ' + str(num_passengers) + ' passengers, ' + str(num_survived) + ' survived.'
print 'The survival rate is ' + str(survival_rate) + ' or '+ str("{0:.0f}%".format(survival_rate * 100))

<type 'list'>
Of 891 passengers, 342 survived.
The survival rate is 0.383838383838 or 38%


**3) How many male passengers were onboard?**

In [104]:
print data[0][4]
type (data[0][4])

male


numpy.string_

In [110]:
# Your code here to calculate num_males


num_males = 0

for val in num_passenger_l: #val is an int
    if ((data[val][4]) == "male"):
        num_males = num_males + 1


print 'There were ' + str(num_males) + ' male passengers onboard.'

There were 577 male passengers onboard.


**4) How many female passengers were onboard?**

In [114]:
# Your code here to calculate num_females

num_females = 0

for val in num_passenger_l: #val is an int
    if ((data[val][4]) == "female"):
        num_females = num_females + 1




print 'There were ' + str(num_females) + ' female passengers onboard.'

There were 314 female passengers onboard.


**5) What is the overall survival rate of male passengers?**

In [120]:
# Your code here to calculate male_survival_rate

#num_survived is the number of people who survived
#num_passenger_surv is an array from 0 to num_survived
#survived_sex was from problem 2, and tracked the sex of all people who survived
#male_survival is a counter for the num of males survived
#male_survival_rate is the survival rate of males
#num_passengers is the total number of passengers

num_passenger_surv = range(0, num_survived)
male_survival = 0

for val in num_passenger_surv:
    if (survived_sex[val] == "male"):
        male_survival = male_survival + 1

male_survival_rate = float(male_survival) / float(num_passengers)


print 'The survival rate of male passengers was ' + str("{0:.2f}%".format(male_survival_rate * 100))

The survival rate of male passengers was 12.23%


**6) What is the overall survival rate of female passengers?**

In [132]:
# Your code here to calculate female_survival_rate
#num_survived = total number of people survived (male or female)


if((num_females + num_males) == (num_passengers)):
    print "every entry is either male or female"
    female_survival = (num_survived - male_survival)
    female_survival_rate = float(female_survival) / float(num_passengers)


print 'The survival rate of female passengers was ' + str("{0:.2f}%".format(female_survival_rate * 100))

every entry is either male or female
The survival rate of female passengers was 26.15%


**7) What is the average age of all passengers onboard?**

In [148]:
# Your code here to calculate avg_age
# HINT: This may be trickier than it first seems. Look at the age values in the raw data file.

type(data[0][5])
#the 'Age' column is all string

sum_age = 0

for val in num_passenger_l:
    sum_age = float(sum_age) + float(data[0][5])
    
avg_age = sum_age / float(num_passengers)

print 'The average age of all passengers onboard was ' + str("{0:.2f}".format(avg_age))

The average age of all passengers onboard was 22.00


**8) What is the average age of passengers who survived?**

In [153]:
# Your code here to calculate avg_age_survived

sum_survived = 0

for val in num_passenger_surv:
    sum_survived = float(sum_survived) + float(data[0][5])

avg_age_survived = sum_survived / num_survived
print sum_survived
print num_survived

print 'The average of age of passengers who survived was ' + str("{0:.2f}".format(avg_age_survived))

7524.0
342
The average of age of passengers who survived was 22.00


**9) What is the average age of passengers who did not survive?**

In [155]:
# Your code here to calculate avg_age_not_survive

sum_died = sum_age - sum_survived 

avg_age_not_survive = float(sum_died) / (num_passengers - num_survived)
print sum_died
print num_passengers - num_survived

print 'The average of age of passengers who did not survive was ' + str("{0:.2f}".format(avg_age_not_survive))

12078.0
549
The average of age of passengers who did not survive was 22.00


**10) At this (early) point in our analysis, what might you infer about any patterns you are seeing in who survived / did not survive?**

I noticed that the average age of passengers who did not survive, average age of passengers who did survive, and the average age of all passengers onboard were all equal to 22.00



**11) How many passengers are in each of the three classes of service (e.g. First, Second, Third?)**

In [157]:
# Your code here
# You do not need to format the output nicely like we did for the questions above.

#assuming Pclass means Cabin Service (First, Second, Third)

Pclass_1 = 0
Pclass_2 = 0
Pclass_3 = 0

for val in num_passenger_l:
    if((data[val][2])=='1'):
        Pclass_1 = Pclass_1 + 1
        
    if((data[val][2])=='2'):
        Pclass_2 = Pclass_2 + 1
        
    if((data[val][2]=='3')):
        Pclass_3 = Pclass_3 + 1

print Pclass_1
print Pclass_2 
print Pclass_3

print Pclass_1 + Pclass_2 + Pclass_3



216
184
491
891


**12) What is the survival rate for passengers in each of the three classes of service?**

In [162]:
# Your code here
# HINT: Averaging of the 1's and 0's in the "Survived" column will give a survival rate.
# We want the survival rate for each passenger class.
# You do not need to format the output nicely.

Pclass_1 = 0
Pclass_1_surv = 0

Pclass_2 = 0
Pclass_2_surv = 0

Pclass_3 = 0
Pclass_3_surv = 0


for val in num_passenger_l:
    if((data[val][2])=='1'):
        Pclass_1 = Pclass_1 + 1
        if((data[val][1])=='1'):
            Pclass_1_surv = Pclass_1_surv + 1
        
    if((data[val][2])=='2'):
        Pclass_2 = Pclass_2 + 1
        if((data[val][1])=='1'):
            Pclass_2_surv = Pclass_2_surv + 1
        
        
    if((data[val][2]=='3')):
        Pclass_3 = Pclass_3 + 1
        if((data[val][1])=='1'):
            Pclass_3_surv = Pclass_3_surv + 1

Tot = Pclass_1_surv + Pclass_2_surv + Pclass_3_surv +  (num_passengers - num_survived)
print Tot

Pclass_1_surv_rate = float(Pclass_1_surv) / float(Pclass_1)
Pclass_2_surv_rate = float(Pclass_2_surv) / float(Pclass_2)
Pclass_3_surv_rate = float(Pclass_3_surv) / float(Pclass_3)

print Pclass_1_surv_rate
print Pclass_2_surv_rate
print Pclass_3_surv_rate

891
0.62962962963
0.472826086957
0.242362525458


**13) How does what we learned in 11) and 12) influence our early conclusions from 10) ?**

We learned from 11 that the bulk of the people onboard were in Cabin 3, or were part of the Lower Class

We learned from 12 that the highest percentage of the people who survived per Cabin class was Cabin 1.

Now I believe that the causation of having 22.0 as an average age across survival/death is due to the fact that there were a lot of children and elders mixed in Cabin 1 who survived, and the bulk age of people in Cabin 3 were 22 and died. 

**14) If we were to build a predictive model, which features in the data do you think we should include in the model and which can we leave out? Why?**

If I were to build a predictive model based off this, I would include the age / PClass / Sex / SibSp / Parch / Fare / Embarked / Name /Survived because their data is homogeneous, or consistent.

I'd leave out Ticket/ Cabin because they are difficult to quantify since they are a mix of letters and numbers in its string, and are unique (independent). Unique in the sense that if I were to classify them, each value would be unique. 